all:
  vars:
    ansible_user: vagrant
  hosts:
    node1:
      ansible_host: 10.99.1.186
      ip: 10.99.1.186
      access_ip: 10.99.1.186
    node2:
      ansible_host: 10.99.1.248
      ip: 10.99.1.248
      access_ip: 10.99.1.248
    node3:
      ansible_host: 10.99.1.182
      ip: 10.99.1.182
      access_ip: 10.99.1.182
    node4:
      ansible_host: 10.99.1.184
      ip: 10.99.1.184
      access_ip: 10.99.1.184
    node5:
      ansible_host: 10.99.1.187
      ip: 10.99.1.187
      access_ip: 10.99.1.187
    node6:
      ansible_host: 10.99.1.180
      ip: 10.99.1.180
      access_ip: 10.99.1.180
  children:
    kube-master:
      hosts:
        node1:
        node2:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
        node4:
        node5:
        node6:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
    heketi-node:
      vars:
        disk_volume_device_1: "/dev/sdb"
      hosts:
        node1:
        node2:
        node3:
        node4:
        node5:
        node6:
    network-storage:
      children:
        gfs-cluster:
    gfs-cluster:
      hosts:
        node3:
        node4:
        node5:
        node6:
