all:
  vars:
    ansible_user: vagrant
    heketi_admin_key: "11elfeinhundertundelf"
    heketi_user_key: "!!einseinseins"
  hosts:
    nodex192:
      ansible_host: 10.99.1.192
      ip: 10.99.1.192
      access_ip: 10.99.1.192
      disk_volume_device_1: "/dev/sdb"
    nodex193:
      ansible_host: 10.99.1.209
      ip: 10.99.1.209
      access_ip: 10.99.1.209
      disk_volume_device_1: "/dev/sdb"
    nodex202:
      ansible_host: 10.99.1.211
      ip: 10.99.1.211
      access_ip: 10.99.1.211
      disk_volume_device_1: "/dev/sdb"
    nodex204:
      ansible_host: 10.99.1.210
      ip: 10.99.1.210
      access_ip: 10.99.1.210
      disk_volume_device_1: "/dev/sdb"
    nodex196:
      ansible_host: 10.99.1.230
      ip: 10.99.1.230
      access_ip: 10.99.1.230
      disk_volume_device_1: "/dev/sdb"
  children:
    kube-master:
      hosts:
        nodex192:
    kube-node:
      hosts:
        nodex193:
        nodex196:
        nodex202:
        nodex204:
    etcd:
      hosts:
        nodex193:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
    heketi-node:
      vars:
        disk_volume_device_1: "/dev/sdb"
      hosts:
        nodex196:
        nodex202:
        nodex204:
    network-storage:
      children:
        gfs-cluster:
    gfs-cluster:
      hosts:
        nodex196:
        nodex202:
        nodex204:
